apiVersion: v1
kind: Pod
metadata:
  name: ambassador-container-demo
  namespace: demo
spec:
  containers:
  # 主容器
  - name: curl
    image: ikubernetes/admin-box:v1.2
    command: ["sleep", "999999"]
  # ambassador容器 作为主容器的正向代理 代理请求kubectl proxy的流量
  - name: ambassador
    image: bitnami/kubectl:latest
    command: ["/bin/sh","-c","kubectl proxy"]
    args:    
    # 传递给 kubectl proxy 的选项,若需要改变默认监听的tcp/8001端口,可以额外附加"--port=NUM"选项
    - --server="https://kubernetes.default.svc"
    - --certificate-authority="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    - --token="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
    - --accept-paths='^.\*'
