apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-poststart-pod
  namespace: demo
spec:
  containers:
    - name: demo
      image: ikubernetes/demoapp:v1.0
      imagePullPolicy: IfNotPresent
      lifecycle:
        # 容器启动后钩子
        postStart:
          exec:
            command:
              # 容器启动后创建一个目录
            - "/bin/sh"
            - "-c"
            - "mkdir /data/"