apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcpsocket-demo
  namespace: demo
spec:
  containers:
    - name: demo
      image: ikubernetes/demoapp:v1.0
      imagePullPolicy: IfNotPresent
      # 定义端口名称
      ports:
      - name: http
        containerPort: 80
      livenessProbe:
        tcpSocket:
          # 使用预定义的端口名称来替代端口号
          port: http
        initialDelaySeconds: 5
        periodSeconds: 5