apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec-demo
  namespace: demo
spec:
  containers:
    - name: demo
      image: ikubernetes/demoapp:v1.0
      imagePullPolicy: IfNotPresent
      # 存活探针
      livenessProbe:
        exec:
          command: 
          - '/bin/sh'
          - '-c'
          - 'test "$(curl -s 127.0.0.1/livez)" = "OK"'
        initialDelaySeconds: 5
        # 每次探测的超时时间
        timeoutSeconds: 1
        periodSeconds: 5