apiVersion: v1
kind: Pod
metadata:
  name: pod-probe-demo
  namespace: demo
spec:
  containers:
    - name: demo
      image: ikubernetes/demoapp:v1.0
      imagePullPolicy: IfNotPresent
      startupProbe:
        exec:
          command:
          - '/bin/sh'
          - '-c'
          - 'test "$(curl -s 127.0.0.1/livez)" = "OK"'
        initialDelaySeconds: 0
        failureThreshold: 3
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: '/livez'
          port: 80
          scheme: HTTP
        initialDelaySeconds: 3
        timeoutSeconds: 2
      readinessProbe:
        httpGet:
          path: '/readyz'
          port: 80
          scheme: HTTP
        initialDelaySeconds: 15
        timeoutSeconds: 2
  restartPolicy: Always