apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
  namespace: demo
spec:
  containers:
  - name: stress
    image: ikubernetes/stress-ng
    command: ["/usr/bin/stress-ng", "-c 1", "-m 1", "--metrics-brief"]
    # 资源控制
    resources:
      # 资源需求: 128MB内存 0.2核逻辑CPU
      requests:
        memory: "128Mi"
        cpu: "200m"
      # 资源限制: 512MB内存 0.4核逻辑CPU
      limits:
        memory: "512Mi"
        cpu: "400m"
