apiVersion: v1
kind: Pod
metadata:
  name: securitycontext-capabilities-demo
  namespace: demo
spec:
  containers:
    - name: demo
      image: ikubernetes/demoapp:v1.0
      imagePullPolicy: IfNotPresent
      # 执行一个修改iptables的命令
      command:
      - "/bin/sh"
      - "-c"
      args: 
      - "/sbin/iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80 && /usr/bin/python3 /usr/local/bin/demo.py"
      securityContext:
        capabilities:
          add:
            # 修改iptables需要赋予用户网络管理员的权限
            # 默认没有赋予容器内用户的这个能力 也就是说默认是无法修改iptables的
          - "NET_ADMIN"
          drop:
          - "CHOWN"