apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container-demo
  namespace: demo
spec:
  containers:
  # sidecar容器 代理主容器的全部流量
  - name: proxy
    image: envoyproxy/envoy-alpine:v1.14.1
  - name: demo
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
    env:
    - name: HOST
      value: "127.0.0.1"
    - name: PORT
      value: "8080"
